name: Build Project

on: 
    workflow_run:
        workflows: ["Run Tests"]
        types:
            - completed    

jobs:
    run-tests:
        uses: ./github/workflows/tests.yml

    build-whoisnet:
        runs-on: ${{ matrix.os }}
        needs: run-tests
        strategy:
            matrix:
                os: [ubuntu-latest, windows-latest]
        steps:
        - name: Restore WhoisNET Dependencies
          run: dotnet restore src/WhoisNET/WhoisNET.sln
        - name: Restore WhoisNET.Client Dependencies
          run: dotnet restore src/WhoisNET.Client/WhoisNET.Client.csproj
        - name: Build WhoisNET
          run: dotnet build src/WhoisNET/WhoisNET.sln --configuration Release
        - name: Build WhoisNET.Client
          run: dotnet build src/WhoisNET.Client/WhoisNET.Client.csproj --configuration Release
        - name: Package WhoisNET (Linux)
          if: ${{ matrix.os == 'ubuntu-latest' }}
          run: |
            dotnet publish src/WhoisNET/WhoisNET.csproj -c Release -o WhoisNET
            cd WhoisNET
            zip -r ../whoisnet-lib-linux-${{ github.ref_name }}.zip .
          shell: bash
        - name: Package WhoisNET Client (Linux)
          if: ${{ matrix.os == 'ubuntu-latest' }}
          run: |
            dotnet publish src/WhoisNET.Client/WhoisNET.Client.csproj -c Release -o WhoisNET
            cd WhoisNET
            zip -r ../whoisnet-client-linux-${{ github.ref_name }}.zip .
          shell: bash
        - name: Package WhoisNET (Windows)
          if: ${{ matrix.os == 'windows-latest' }}
          run: |
            dotnet publish src/WhoisNET/WhoisNET.csproj -c Release -o WhoisNET
            Compress-Archive -Path WhoisNET/* -DestinationPath whoisnet-win-lib-${{ github.ref_name }}.zip
          shell: pwsh
        - name: Package WhoisNET Client (Windows)
          if: ${{ matrix.os == 'windows-latest' }}
          run: |
            dotnet publish src/WhoisNET.Client/WhoisNET.Client.csproj -c Release -o WhoisNET
            Compress-Archive -Path WhoisNET.Client/* -DestinationPath whoisnet-win-client-${{ github.ref_name }}.zip
          shell: pwsh
