name: Run Tests

on:
  push:
    tags:
      - 'v*'

jobs:
    run-tests:
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [ubuntu-latest, windows-latest]
        steps:
            - uses: actions/checkout@v4
            - name: Setup node
              uses: actions/setup-node@v4
              with:
                node-version: '20'
            - name: Setup .NET
              uses: actions/setup-dotnet@v4
              with:
                dotnet-version: '8.0'
            - name: Restore Dependencies
              run: dotnet restore src/WhoisNET/WhoisNET.sln
            - name: Run WhoisNET Tests
              run: dotnet test src/WhoisNET.Tests/WhoisNET.Tests.csproj --verbosity normal
            - name: Run WhoisNET.Client Tests
              run: dotnet test src/WhoisNET.Client.Tests/WhoisNET.Client.Tests.csproj --verbosity normal
